import { RetrievalResult } from './retrieval.interface';

export interface Citation {
  startIndex: number;
  endIndex: number;
  chunkId: string;
  documentId: string;
  pageNumber: number | null;
  excerpt: string;
}

export interface ICitationProvider {
  /**
   * Identifies references inside generated text to trace chunks from which information was retrieved.
   * @param responseText The text generated by the LLM.
   * @param contexts The retrieved contexts containing source metadata.
   * @returns A list of verified Citations detailing start/end index and source IDs.
   */
  generateCitations(responseText: string, contexts: RetrievalResult[]): Promise<Citation[]>;
}

export class PlaceholderCitationProvider implements ICitationProvider {
  async generateCitations(_responseText: string, _contexts: RetrievalResult[]): Promise<Citation[]> {
    throw new Error('Method not implemented. ICitationProvider is a Phase 1 placeholder.');
  }
}
