-- ─────────────────────────────────────────────────────────────────────────────
-- Migration: 0003_ai_evaluations
-- Phase 4: AI Evaluation Dashboard
-- Creates the ai_evaluations table that stores granular quality and
-- performance metrics for every RAG answer generated by the system.
-- This table is PURELY ADDITIVE — no existing tables are altered.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "ai_evaluations" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,

  -- Links to the exact assistant message this evaluation covers
  "message_id" uuid NOT NULL,

  -- Links to the conversation session
  "conversation_id" uuid NOT NULL,

  -- The user who triggered the RAG query
  "user_id" uuid NOT NULL,

  -- Optional: if the query was scoped to a single document
  "document_id" uuid,

  -- The original user question text
  "query" text NOT NULL,

  -- ── Latency Metrics ──────────────────────────────────────
  "retrieval_latency_ms" integer NOT NULL,
  "llm_latency_ms" integer NOT NULL,
  "total_latency_ms" integer NOT NULL,

  -- ── Retrieval Quality Metrics ─────────────────────────────
  "chunks_retrieved" integer NOT NULL,
  "citations_count" integer NOT NULL DEFAULT 0,
  "avg_similarity_score" real NOT NULL DEFAULT 0,
  "top_similarity_score" real NOT NULL DEFAULT 0,

  -- ── Token Usage ───────────────────────────────────────────
  "tokens_estimated" integer NOT NULL DEFAULT 0,

  -- ── Quality / Evaluation Scores ───────────────────────────
  -- citation_coverage = citations_count / chunks_retrieved (0–1)
  "citation_coverage" real NOT NULL DEFAULT 0,
  -- retrieval_precision = avg_similarity_score proxy (0–1)
  "retrieval_precision" real NOT NULL DEFAULT 0,
  -- retrieval_recall = null placeholder (requires ground-truth labels)
  "retrieval_recall" real,
  -- hallucination_score = 1 - citation_coverage (0–1 rule-based proxy)
  "hallucination_score" real NOT NULL DEFAULT 0,
  -- answer_completeness = min(1, word_count / 50) heuristic
  "answer_completeness" real NOT NULL DEFAULT 0,

  -- Was Ollama running when this answer was generated?
  "ollama_online" boolean NOT NULL DEFAULT true,

  "created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint

-- Foreign key: evaluation → message
DO $$ BEGIN
 ALTER TABLE "ai_evaluations" ADD CONSTRAINT "ai_evaluations_message_id_messages_id_fk"
   FOREIGN KEY ("message_id") REFERENCES "public"."messages"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint

-- Foreign key: evaluation → conversation
DO $$ BEGIN
 ALTER TABLE "ai_evaluations" ADD CONSTRAINT "ai_evaluations_conversation_id_conversations_id_fk"
   FOREIGN KEY ("conversation_id") REFERENCES "public"."conversations"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint

-- Foreign key: evaluation → user
DO $$ BEGIN
 ALTER TABLE "ai_evaluations" ADD CONSTRAINT "ai_evaluations_user_id_users_id_fk"
   FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint

-- Foreign key: evaluation → document (nullable, set null on delete)
DO $$ BEGIN
 ALTER TABLE "ai_evaluations" ADD CONSTRAINT "ai_evaluations_document_id_documents_id_fk"
   FOREIGN KEY ("document_id") REFERENCES "public"."documents"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint

-- Index: speed up user-scoped dashboard queries (most common access pattern)
CREATE INDEX IF NOT EXISTS "ai_evaluations_user_id_idx" ON "ai_evaluations" ("user_id");

-- Index: speed up date-range filtering for charts
CREATE INDEX IF NOT EXISTS "ai_evaluations_created_at_idx" ON "ai_evaluations" ("created_at");

-- Index: speed up document-scoped filtering
CREATE INDEX IF NOT EXISTS "ai_evaluations_document_id_idx" ON "ai_evaluations" ("document_id");
